# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
# CONFIG_ZMK_DISPLAY=y

# Define o nome do teclado para "Halley"
CONFIG_ZMK_KEYBOARD_NAME="Halley"

# Ativa o subsistema de display do Zephyr/ZMK
# CONFIG_ZMK_DISPLAY=y

# Desliga os displays após 15 segundos de inatividade (15000 ms)
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
# CONFIG_ZMK_IDLE_TIMEOUT=15000

# Habilita o suporte ao ZMK Studio no firmware
CONFIG_ZMK_STUDIO=y

# (Opcional) Desativa o bloqueio automático de segurança do Studio.
# Se deixar 'y' (padrão), você precisará mapear uma tecla de "desbloquear" (&studio_unlock) 
# no seu mapa para conseguir alterar o layout no app. Definir como 'n' facilita sua vida.
CONFIG_ZMK_STUDIO_LOCKING=n