# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
# CONFIG_ZMK_DISPLAY=y

# Define o nome do teclado para "Halley"
CONFIG_ZMK_KEYBOARD_NAME="Halley"

# Ativa o subsistema de display do Zephyr/ZMK
# CONFIG_ZMK_DISPLAY=y

# Desliga os displays após 15 segundos de inatividade (15000 ms)
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
# CONFIG_ZMK_IDLE_TIMEOUT=15000

# Habilita o suporte ao ZMK Studio no firmware
CONFIG_ZMK_STUDIO=y

# (Opcional) Desativa o bloqueio automático de segurança do Studio.
# Se deixar 'y' (padrão), você precisará mapear uma tecla de "desbloquear" (&studio_unlock) 
# no seu mapa para conseguir alterar o layout no app. Definir como 'n' facilita sua vida.
CONFIG_ZMK_STUDIO_LOCKING=n

# Ativa o modo de sono profundo
CONFIG_ZMK_SLEEP=y

# Tempo para entrar em sono profundo: 15 minutos (900.000 milissegundos)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Aumenta a potência de transmissão do Bluetooth (padrão é +0, o máximo é +8)
# Melhora drasticamente a estabilidade entre as duas metades
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Reporta o nível de bateria de ambas as metades para o sistema operacional
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y